### ISSUE TITLE
Edit Footer on lesson html pages

### ISSUE THREAD

**Issue by sabaferdous12** [LearnToDiscover/varnish#11]
1. The lesson footer contains text which is hyperlinked to carpentries. We want to remove those. 

![Image](https://github.com/LearnToDiscover/varnish/assets/7863996/88f64627-5b9c-4082-b923-726e1eedd290)

In this footer we only want to keep these 2 lines and remove everything else:

> Template licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by-sa/4.0/) by [The Carpentries](https://carpentries.org/)
>
> Built with [sandpaper (0.16.4)](https://github.com/LearnToDiscover/sandpaper/tree/l2d), [pegboard (0.7.5)](https://github.com/carpentries/pegboard/tree/a32a7836d4455f407c3cafe8ab95edc636e5e919), and [varnish (1.0.2)](https://github.com/LearnToDiscover/varnish/tree/7ac5e27a3dfed3a59ec1e5fcb0b719d430806598)

2. Secondly, we want to change the URL icon. Right now it looks like this

![Image](https://github.com/LearnToDiscover/varnish/assets/7863996/8e4897e0-8660-41a0-bc75-b6aada906186)

But we want to replace carpentries wheel with L2D brain logo:

![logo_colour_full_darkbg (1)](https://github.com/LearnToDiscover/varnish/assets/7863996/36d85860-d1d7-48bc-b549-fbfc8397beed)

You think this can done anytime soon, please?

**Comment by sabaferdous12** [comment]
@milanmlft 

Can we just remove this line from the footer:

Template licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by-sa/4.0/) by [The Carpentries](https://carpentries.org/)

Its misleading for our IP licensing.

**Comment by milanmlft** [comment]
@sabaferdous12 please don't put the same request in multiple places, it's confusing. I'm going to close this issue again and move https://github.com/LearnToDiscover/varnish/issues/23 to `varnish` (where it should be).
