### ISSUE TITLE
Widening: 'objectives' box and main text.

### ISSUE THREAD

**Issue by L2D-admin** [LearnToDiscover/varnish#16]
At the top of an episode, there's a blue 'overview' box. Under this heading come two columns: 'Objectives' and 'Questions'. Currently, the 'Objectives' feel squeezed and narrow: could we widen this column to more evenly distribute the text between the two columns? 

Furthermore, the main body of the text materials feel like they're in a slightly too-narrow constraint, overall. Is there a chance we could use just a little bit more of the screen real-estate, and widen this? Not too much, as there's a nice trade-off between easy legibility when it's narrow, and fuller use of the blank space. Thank you!

**Comment by milanmlft** [comment]
> Furthermore, the main body of the text materials feel like they're in a slightly too-narrow constraint, overall. Is there a chance we could use just a little bit more of the screen real-estate, and widen this? Not too much, as there's a nice trade-off between easy legibility when it's narrow, and fuller use of the blank space. Thank you!

I would advise against this as it would require a lot of changes to `varnish` and create more opportunities for merge conflicts when we want to pull updates from the upstream Carpentries repo. And in any case, you can just collapse the sidebar to have a wider view of the main text.

Note also that the Carpentries have gone through extensive rounds of accessibility testing to make sure their template is optimally readable on a wide range of devices and for various accessibility requirements. So I'm reluctant to temper with this too much.
