### ISSUE TITLE
Make the side menu 'sticky' when scrolling

### ISSUE THREAD

**Issue by sabaferdous12** [LearnToDiscover/varnish#24]
Is there any way that we could lock/freeze the side menu while scrolling through the page.

**Comment by milanmlft** [comment]
Looks like this is also a request in the upstream Carpentries repo that has been open for a while: https://github.com/carpentries/varnish/issues/16
If I find a solution (this might be a big if), I'll probably contribute it to the Carpentries repo and then merge here.

**Comment by sabaferdous12** [comment]
Sounds good to me
